name: swift
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.9.0
  feather_icons: ^1.2.0
  flutter:
    sdk: flutter
  flutter_map: ^8.2.1
  flutter_osm_plugin: ^1.4.2
  google_fonts: ^6.3.0
  google_places_autocomplete_text_field: ^2.0.3
  http: ^1.5.0
  ionicons: ^0.2.2
  jwt_decoder: ^2.0.1
  latlong2: ^0.9.1
  material_floating_search_bar_2: ^0.5.0
  modal_bottom_sheet: ^3.0.0
  new_loading_indicator: ^1.0.2
  search_map_place_updated: ^0.1.0
  shared_preferences: ^2.5.3
  geolocator: ^12.0.0
  phone_form_field: ^10.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/box.png
    - assets/images/hands.png
    - assets/images/request.png
    - assets/images/rider.png
    - assets/images/logo.png
