// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhJBl7sZDw4TltiHZi-t4B9TX0WEpkVpM',
    appId: '1:932610158988:web:795c9b7d4e0801ab7f66a9',
    messagingSenderId: '932610158988',
    projectId: 'swift-bf821',
    authDomain: 'swift-bf821.firebaseapp.com',
    storageBucket: 'swift-bf821.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTmKfCAPzUA_V9XYQYuwksaDqiO272ss',
    appId: '1:932610158988:android:51cd5e4e44c8b8117f66a9',
    messagingSenderId: '932610158988',
    projectId: 'swift-bf821',
    storageBucket: 'swift-bf821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RmeEturA691dgSHK4gG1DBPfBB2F_Y0',
    appId: '1:932610158988:ios:e35734519ecb8eea7f66a9',
    messagingSenderId: '932610158988',
    projectId: 'swift-bf821',
    storageBucket: 'swift-bf821.firebasestorage.app',
    iosBundleId: 'com.example.swift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_RmeEturA691dgSHK4gG1DBPfBB2F_Y0',
    appId: '1:932610158988:ios:e35734519ecb8eea7f66a9',
    messagingSenderId: '932610158988',
    projectId: 'swift-bf821',
    storageBucket: 'swift-bf821.firebasestorage.app',
    iosBundleId: 'com.example.swift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhJBl7sZDw4TltiHZi-t4B9TX0WEpkVpM',
    appId: '1:932610158988:web:8645a2bbbb2406ac7f66a9',
    messagingSenderId: '932610158988',
    projectId: 'swift-bf821',
    authDomain: 'swift-bf821.firebaseapp.com',
    storageBucket: 'swift-bf821.firebasestorage.app',
  );
}
